#!/bin/sh

echo "== Removing Docker Containers == "
echo "WARNING! This will remove all data in the database."

read -p "Are you sure you want to continue? <y/N> " prompt

if [[ $prompt == "y" || $prompt == "Y" || $prompt == "yes" || $prompt == "Yes" ]]
then
  docker-compose down
  echo "\n== Done! == "

else
  echo "\n== Skipping! == "
fi


